import test from "node:test";
import assert from "node:assert/strict";
import { buildRailwayTimetableOperationView, TIMETABLE_OPERATION_VIEW_SCHEMA } from "../src/map/railway-timetable-operation-view.mjs";
const stations = [{ id: "a", location: [139, 35] }, { id: "b", location: [139.1, 35.1] }];
const timetables = [{ id: "tt:1", status: "active", dayType: "weekday", requestedPaths: 2, acceptedPaths: [{ pathId: "p" }] }];
const lines = [{ id: "line:1", stationIds: ["a", "b"], timetableDispatches: { weekday: { timetableId: "tt:1", dayType: "weekday", serviceId: "service:1", departureMinutes: [360], missedDepartures: 0 } } }];
test("read-only view shows the factual dispatch and train provenance", () => { const input = { timetables: structuredClone(timetables), lines: structuredClone(lines), stations: structuredClone(stations), trains: [{ id: 9, lineId: "line:1", serviceStationIds: ["a", "b"], segIndex: 0, dir: 1, t: .5, timetableId: "tt:1", managementServiceId: "service:1" }] }; const before = structuredClone(input); const view = buildRailwayTimetableOperationView(input); assert.equal(view.schema, TIMETABLE_OPERATION_VIEW_SCHEMA); assert.equal(view.lines[0].schedules[0].status, "active"); assert.deepEqual(view.trains[0].location, [139.05, 35.05]); assert.equal(view.trains[0].managementServiceId, "service:1"); assert.deepEqual(input, before); });
test("unknown timetable and position stay unknown", () => { const view = buildRailwayTimetableOperationView({ lines: [{ id: "l", stationIds: ["missing"], timetableDispatches: { weekday: { timetableId: "gone" } } }], trains: [{ id: 1, serviceStationIds: ["missing"], segIndex: 0, dir: 1, t: .2 }] }); assert.deepEqual(view.missing.timetableRecords, ["gone"]); assert.equal(view.lines[0].shape.points, null); assert.equal(view.trains[0].location, null); });
test("display names and input order do not create a new association", () => { const a = buildRailwayTimetableOperationView({ timetables: [{ ...timetables[0], name: "A" }], lines, stations }); const b = buildRailwayTimetableOperationView({ timetables: [{ ...timetables[0], name: "B" }], lines: [...lines].reverse(), stations: [...stations].reverse() }); assert.deepEqual(a, b); });
