import { defineConfig } from 'vite';
import { viteStaticCopy } from 'vite-plugin-static-copy';
import path from 'path';

export default defineConfig({
  resolve: {
    alias: {
      'react/jsx-runtime': path.resolve(__dirname, 'src/types/react.ts'),
      'react': path.resolve(__dirname, 'src/types/react.ts'),
    },
  },
  esbuild: {
    jsx: 'automatic',
    jsxImportSource: 'react',
    keepNames: true,
  },
  build: {
    lib: {
      entry: path.resolve(__dirname, 'src/main.ts'),
      formats: ['iife'],
      name: 'SubwayMod',
      fileName: () => 'index.js',
    },
    outDir: 'dist',
    minify: false,
    rollupOptions: {
      output: {
        entryFileNames: 'index.js',
      },
    },
  },
  plugins: [
    viteStaticCopy({
      targets: [
        {
          src: 'manifest.json',
          dest: '.',
        },
        {
          // Generated by ../../scripts/export-subway-builder-*.mjs (see ../../subway-builder-export/README.md).
          // buildings_index.all.json is ~588 MB (all 23 wards) - the copy step is slow, not stuck.
          // roads.chiyoda.geojson is real but Chiyoda ward only - a documented gap, not a build error.
          src: '../../subway-builder-export/{demand_data.chome.json,buildings_index.all.json,roads.chiyoda.geojson}',
          dest: 'data',
        },
      ],
    }),
  ],
});
